import { AssistantAnswer } from "@/lib/ai/assistant";

/**
 * Optional narration layer: if ANTHROPIC_API_KEY is set, ask an LLM to
 * rephrase the deterministic engine's answer in a warmer voice. The engine's
 * numbers are never regenerated by the model — it receives them as fixed
 * facts and is only allowed to restyle the sentence. If no key is set, or
 * the call fails for any reason, the deterministic answer is returned
 * untouched so the assistant always works standalone.
 */
export async function narrate(base: AssistantAnswer, question: string): Promise<string> {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) return base.answer;

  try {
    const res = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "content-type": "application/json",
        "x-api-key": apiKey,
        "anthropic-version": "2023-06-01",
      },
      body: JSON.stringify({
        model: "claude-haiku-4-5-20251001",
        max_tokens: 200,
        system:
          "You restyle a fantasy football assistant's answer to sound natural and friendly. You MUST NOT change, add, or remove any number, player name, or factual claim — only adjust tone and sentence flow.",
        messages: [{ role: "user", content: `Question: ${question}\nFactual answer to restyle: ${base.answer}` }],
      }),
      signal: AbortSignal.timeout(8000),
    });
    if (!res.ok) return base.answer;
    const data = await res.json();
    const text = data?.content?.[0]?.text;
    return typeof text === "string" && text.length > 0 ? text : base.answer;
  } catch {
    return base.answer;
  }
}
